apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deploy
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: simple-web
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Hello from app1."
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CONTAINER_IMAGE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: networking.k8s.io/v1
kind : Ingress
metadata:   
  name  : app1-ingress-controller
spec: 
    rules:
    - host: "app1.com"
      http: 
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: app1-service
                port: 
                  number: 80

---