# -*- mode: ruby -*-
# vi: set ft=ruby :

# Master node name
login   = "apearl"
# Master node static IP
node_ip = "192.168.42.110"

Vagrant.configure("2") do |config|
  config.vm.box     = "generic/centos7"
  config.vm.box_url = "https://app.vagrantup.com/generic/boxes/centos7/versions/3.6.14/providers/virtualbox.box"
  #config.vm.box_url = "file:///goinfre/apearl/e5907522-6df5-4570-9c1c-6ec9abd45ca5"
  
#disabled: false, create: true
# set directories for sync between host and master
  config.vm.synced_folder ".", "/vagrant", disabled: false, create: true
# set hostname to variable
  config.vm.hostname = "#{login}S-p2"
# set static IP for master node
  config.vm.network "private_network", ip: node_ip
# set instrument virtualbox for apply configs
  config.vm.provider "virtualbox" do |v|
    # set static connection with IP
    v.customize ["modifyvm", :id, "--name", config.vm.hostname]
    # set configs for launch virtual machine like CPU and memory 
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 4]
  end
  # set configs for implement bash scripts in virtual machine
  config.vm.provision "shell", privileged: false, path: "scripts/server.sh", env: {"NODE_IP": node_ip}
  config.vm.provision "shell", privileged: false, path: "scripts/apply.sh"
end
