login   = "gjigglyp"
node_ip = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_url = "file:///home/denis/focal-server-cloudimg-amd64-vagrant.box"

  ##config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/focal64/versions/20220804.0.0/providers/virtualbox.box"

  config.vm.synced_folder ".", "/vagrant", disabled: false, create: true

  config.vm.hostname = "#{login}S"
  config.vm.network "private_network", ip: node_ip
  config.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8888, host: 8888, protocol: "tcp"


  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--name", config.vm.hostname]
    v.customize ["modifyvm", :id, "--memory", 4096]
    v.customize ["modifyvm", :id, "--cpus", 4]
  end
  config.vm.provision "shell", privileged: false, path: "scripts/instl.sh"
end